function hsics_psnr_figure(results_folder,optical_list,markerstyles,colors)
% HSICS_PSNR_FIGURE
% Generate the average reconstruction PSNR figures
%
% Usage:
% HSICS_PSNR_FIGURE;
% HSICS_PSNR_FIGURE(results_folder);
% HSICS_PSNR_FIGURE(results_folder,optical_list);
% HSICS_PSNR_FIGURE(results_folder,optical_list,markerstyles);
%
% results_folder is the 'matfiles' folder containing the files generated by
% hsics_gather_psnr. 
%
% optical_list is the list of curves that should be displayed on the plot.
% By default, all of them are displayed.
% 
% markerstyles (cell) and colors (n by 3 array) are the markerstyles and
% colors that should be used for each optical_setup.
%
% Example (used in the paper):
%
%     optical_list = {'InFocus_mosaic';
%                     'InFocus_random';
%                     'OffFocus_mosaic_multi';
%                     'OffFocus_mosaic_11px_multi';
%                     'OffFocus_mosaic_5px_multi'};
%     markerstyles = {'s';
%                     'd';
%                     '.';
%                     'o';
%                     '>'};
%     colors = [0.4,0.1,0.5;
%               0.9,0.5,0.0;
%               0.7,0.2,0.1;
%               0.1,0.5,0.1;
%               0.0,0.0,0.0];
%
% NB: optimization of the figure layout is left at the discretion of the
% user. See the matlab2tikz toolbox for exporting in LaTeX.
% 
% see also hsics_gather_psnr
%
% see README.txt
%
% Author: K. Degraux
% Date: 8/01/2018
%
%  (c) UCLouvain 2018


if nargin<1
    results_folder = 'matfiles';
end
if nargin<2
    optical_list = {'InFocus_mosaic';
                    'InFocus_random';
                    'OffFocus_mosaic_multi';
                    'OffFocus_mosaic_11px_multi';
                    'OffFocus_random_multi';
                    'OffFocus_random_11px_multi';
                    'OffFocus_mosaic';
                    'OffFocus_mosaic_11px';
                    'OffFocus_random';
                    'OffFocus_random_11px';
                    'OffFocus_mosaic_5px_multi'};
    % In the paper:
%     optical_list = {'InFocus_mosaic';
%                     'InFocus_random';
%                     'OffFocus_mosaic_multi';
%                     'OffFocus_mosaic_11px_multi';
%                     'OffFocus_mosaic_5px_multi'};
end
if nargin<3
    markerstyles = {'s';
                    'd';
                    '.';
                    'o';
                    '+';
                    '*';
                    'x';
                    'p';
                    'v';
                    '^';
                    '>'};
    % In the paper:
%     markerstyles = {'s';
%                     'd';
%                     '.';
%                     'o';
%                     '>'};
end
if nargin<4
    colors = [0.4,0.1,0.5;
              0.9,0.5,0.0;
              0.7,0.2,0.1;
              0.1,0.5,0.1;
              0.2,0.3,0.6;
              0.7,0.7,0.2;
              0.1,0.5,0.9;
              0.5,0.9,0.0;
              0.1,0.1,0.8;
              0.9,0.1,0.6;
              0.0,0.0,0.0];
	% In the paper
%     colors = [0.4,0.1,0.5;
%               0.9,0.5,0.0;
%               0.7,0.2,0.1;
%               0.1,0.5,0.1;
%               0.0,0.0,0.0];
end

linestyles={'-',':'};

m_n       = [1,2,3,4].^2/16;
n_q       = 4;
n_snr     = 2;
n_optical = length(optical_list);

psnr_curves = zeros(n_optical,n_q,n_snr);
for optical_id = 1:n_optical
    psnr_file = load([results_folder,filesep,optical_list{optical_id},'_psnr.mat']);
    psnr_curves(optical_id,:,:) = mean(psnr_file.psnr,1);
    for snr_id = 1:2
        figure(snr_id);
        plot(m_n,psnr_curves(optical_id,:,snr_id),...
             'marker',markerstyles{optical_id},...
             'linestyle',linestyles{snr_id},...
             'color',colors(optical_id,:),...
             'linewidth',2); hold on;
    end
end
for snr_id = 1:2
    figure(snr_id);
    xlabel('m/n');
    ylabel('PSNR (dB)');
    legend(strrep(optical_list,'_',' '),'location','northeastoutside');
    hold off;
end

end